### ISSUE TITLE
User should be warned of rm(list=ls(all=TRUE))

### ISSUE THREAD

**Issue by johnbaums** [ARCCSS-extremes/climpact2#34]
I think that the user should be warned (e.g., in the manual) that climpact2.GUI.r will remove all objects in the workspace (https://github.com/ARCCSS-extremes/climpact2/blob/b18de50/climpact2.GUI.r#l49).

**Comment by heroldn** [comment]
I'm commenting this out in our current un-released version. I'm unsure the reason this was included in the first place, we are beginning testing on a new version of the software so will see if there are ramifications.
