### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by chiluf** [ARCCSS-extremes/climpact2#35]
Greetings from Zambia.

We are using the climPACT2 to calculate the ET-SCI indices for stations in Zambia. However we are getting the error shown in the attached screenshot image.

We will be grateful for any guidance to resolve this error.

many thanks
![climpact2-error](https://cloud.githubusercontent.com/assets/559368/14564558/59f5c4ca-0327-11e6-955c-8c2dd9d44371.png)
![climpact2-error](https://cloud.githubusercontent.com/assets/559368/14564571/6aea3d10-0327-11e6-8985-c1d00412a309.png)

**Comment by heroldn** [comment]
Hi, thanks for your detailed message. Could I please get you to try the
latest version of the software
https://github.com/ARCCSS-extremes/climpact2/archive/master.zip

And could you send me the input data you are trying to load.

Regards

Nicholas.
