### ISSUE TITLE
Error in respc$stats[5, a] : subscript out of bounds

### ISSUE THREAD

**Issue by chiluf** [ARCCSS-extremes/climpact2#36]
Loading required package: PCICt
# Package lmomco (2.1.4) loaded [try lmomcoNews()].
# Package SPEI (1.6) loaded [try SPEINews()].
[1] "LOADING CLIMDEX INPUT OBJECT..."
[1] "CHECKING FOR TEMPERATURE OUTLIERS..."
[1] "CALCULATING MEANS AND STANDARD DEVIATIONS..."
[1] "TESTING DATA, PLEASE WAIT..."
_**Error in respc$stats[5, a] : subscript out of bounds**_

How to resolve this error

**Comment by heroldn** [comment]
Closing this issue as it is resolved. This bug was due to QC code assuming there would be non zero precipitation values in at least one day in every month.
