### ISSUE TITLE
Test Basic Linux

### ISSUE THREAD

**Issue by heroldn** [ARCCSS-extremes/climpact2#38]
Run through all three uses of ClimPACT2 in a Linux distribution to ensure program runs without error in GUI or command line.

**Comment by yilingliu** [comment]
There are lots of softwares beginning with "r" in my Linux Muon list. I installed "r-base" through Linux Muon Package Manager. It seems to be the right one.

**Comment by heroldn** [comment]
Ok, so this is a not so uncommon issue and means you need the "BWidget" package in linux installed. Can you find this in Muon and install it?

**Comment by yilingliu** [comment]
yes, have installed it

**Comment by yilingliu** [comment]
There are warnings after running  command source('installers/climpact2.ncdf.installer.r'). Is it fine?
> warnings()
Warning messages:
1: package ‘abind’ is not available (for R version 3.0.3)
2: package ‘bitops’ is not available (for R version 3.0.3)
3: package ‘Rcpp’ is not available (for R version 3.0.3)
4: package ‘caTools’ is not available (for R version 3.0.3)
5: package ‘PCICt’ is not available (for R version 3.0.3)
6: package ‘SPEI’ is not available (for R version 3.0.3)
7: package ‘climdex.pcic’ is not available (for R version 3.0.3)
8: package ‘snow’ is not available (for R version 3.0.3)
9: package ‘udunits2’ is not available (for R version 3.0.3)
10: package ‘functional’ is not available (for R version 3.0.3)
11: package ‘proj4’ is not available (for R version 3.0.3)
12: In install.packages("./pcic_packages/ncdf4.helpers_0.3-3.tar.gz",  ... :
  installation of package ‘./pcic_packages/ncdf4.helpers_0.3-3.tar.gz’ had non-zero exit status
13: In install.packages("./pcic_packages/climdex.pcic.ncdf.climpact.tar.gz",  ... :
  installation of package ‘./pcic_packages/climdex.pcic.ncdf.climpact.tar.gz’ had non-zero exit status

**Comment by heroldn** [comment]
This indicates that those packages aren't then being installed. So you
wouldn't be able to run the climpact2.ncdf.wrapper.r file. Is this the
case, could you run the software after this?

**Comment by yilingliu** [comment]
The last problem seemed to happen when I used O-Cloud CRAN mirror to download the required packages. Everything is fine if I use Australian http. And should be careful that there are several applications looking like udunits2 and proj4 in Linux muon, but only  libudunits2-dev and libproj-dev  work.
All  three uses in Linux have been tested, and work well now.
