### ISSUE TITLE
Basic MacOS

### ISSUE THREAD

**Issue by heroldn** [ARCCSS-extremes/climpact2#39]
Run through all three uses of ClimPACT2 in MacOS to ensure program runs without error in GUI or command line.

**Comment by yilingliu** [comment]
when I run "Rscript climpact2.ncdf.wrapper.r" on my MacOs command line, there was an error information "Error in FUN(X[[i]], ...) : 
  Units kg m-2 d-1 and kg m-2 d-1 are not convertible" . After "brew install udunits", this error information disappeared.

**Comment by yilingliu** [comment]
GUI runs well for now.
I modified climpact2.ncdf.thresholds.wrapper.r as follows:
library(climdex.pcic.ncdf)
# list of one to three input files. e.g. c("a.nc","b.nc","c.nc")
input.files = c("./sample_data/climpact2.sampledata.gridded.1991-2010.nc")
# list of variable names according to above file(s)
vars=c(tmax="tmax", tmin="tmin", prec="precip")
# output file name
output.file = "./output/thresholds.1991-2010.nc"
# author data
author.data=list(institution="My University", institution_id="MU")
# reference period
base.range=c(1991,2010)

After "Rscript climpact2.ncdf.thresholds.wrapper.r", there was an error information as follows:
"Loading required package: PCICt
Loading required package: methods
Error in paste(base.range, collapse = "-") : 
  argument "base.range" is missing, with no default
Calls: create.thresholds.from.file ... put.ETCCDI.atts -> <Anonymous> -> ncatt_put_inner -> paste
Execution halted"

**Comment by yilingliu** [comment]
If I source("ancillary/climpact2.batch.installer.r") as instructed by the users' guide, error occurs: "cannot open file 'ancillary/climpact2.batch.installer.r': No such file or directory."  My climpact2.batch.installer.r is under folder installers.

**Comment by yilingliu** [comment]
There is no individual station files under sample_data folder.

**Comment by heroldn** [comment]
Thanks, corrected.

**Comment by heroldn** [comment]
Hi Yiling

Could you please download climpact again and try.
https://github.com/ARCCSS-extremes/climpact2/archive/overhaul-batch-pcic.ncdf.zip

I had updated some attributes to be written out for index files but hadn't
changed the threshold file routine.

Cheers

Nick.

**Comment by yilingliu** [comment]
Hi Nick,
Sure.

Cheers,
Yiling

**Comment by yilingliu** [comment]
The use "Calculating the indices from netCDF data" is doing fine on my MacOS now.

**Comment by yilingliu** [comment]
"Batch processing multiple station files" is also doing well now.

**Comment by heroldn** [comment]
It sounds like you were able to run the GUI, calculate the indices on a netcdf file and run in batch mode. I'll close this then.
