### ISSUE TITLE
Basic Windows

### ISSUE THREAD

**Issue by heroldn** [ARCCSS-extremes/climpact2#40]
Run through the GUI on Windows to ensure program runs without error in GUI or command line.

**Comment by yilingliu** [comment]
What's wrong with this when I type  source('climpact2.GUI.r') :
[1] "******************************"
[1] "Installing the following required packages...bitops"      
[2] "Installing the following required packages...Rcpp"        
[3] "Installing the following required packages...caTools"     
[4] "Installing the following required packages...PCICt"       
[5] "Installing the following required packages...SPEI"        
[6] "Installing the following required packages...climdex.pcic"
--- Please select a CRAN mirror for use in this session ---
Warning: failed to download mirrors file (cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'); using local file '//INFPWFS1401.ad.unsw.edu.au/Staff110$/z5100874/R/R-3.3.0/doc/CRAN_mirrors.csv'
Warning: unable to access index for repository https://cloud.r-project.org/src/contrib:
  cannot open URL 'https://cloud.r-project.org/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cloud.r-project.org/bin/windows/contrib/3.3:
  cannot open URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/PACKAGES'
[1] R version 3.3.0 detected.
Error in library(climdex.pcic) : 
  there is no package called ‘climdex.pcic’
In addition: Warning messages:
1: In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl failed: 'The certificate authority is invalid or incorrect'
2: packages ‘bitops’, ‘Rcpp’, ‘caTools’, ‘PCICt’, ‘SPEI’, ‘climdex.pcic’ are not available (for R version 3.3.0)

**Comment by heroldn** [comment]
Ok we seemed to have got this working. I think it was mostly that Windows was being virtualised through a Linux box.

**Comment by yilingliu** [comment]
Yes, I think it's working. The only thing is that like in Linux the above problem seemed to happen when I used O-Cloud CRAN mirror to download the required packages, whereas everything is fine if I use Australian http.
