### ISSUE TITLE
No confirmation button for user defined title in GUI

### ISSUE THREAD

**Issue by tammasloughran** [ARCCSS-extremes/climpact2#46]
When I load the sample station file for sydney and click the step 2 button, it requests a title for plots. But there is no confirmation button so I can't continue. Hitting enter does nothing. What's the deal here?

**Comment by heroldn** [comment]
I'm guessing the BWidget package isn't installed on your system. Can you do
a search for "BWidget" in your package manager and install if you find it,
if not we'll chat offline.

**Comment by tammasloughran** [comment]
Okay, yep that fixed it. Thanks.
