### ISSUE TITLE
Batch processing multiple station files with R in windows

### ISSUE THREAD

**Issue by Wendso** [ARCCSS-extremes/climpact2#56]
Hello
I have 85 stations for which I want to use Climpact. The Rscript provided seems to be for Linux. Can you help me with tutorial on how to make it on Windows? I have prepared all the stations files and the metadata file is also okay. But I am stuck because on the section 5 of user guide it requires command line arguments to be passed on Linux. How do I do it if I have Windows? Please help me?
![capture1](https://user-images.githubusercontent.com/33805298/43520607-f0f4479e-959b-11e8-97af-1a0977dfa17d.JPG)

**Comment by heroldn** [comment]
Hi Wendso

In windows there is in fact a "Rscript.exe" executable. It's in the directory where R is installed. For example, on my PC it is in C:\Program Files\R\R-3.5.1\bin.

You want to open a Windows command prompt (similar to a Linux terminal) by pressing the Windows button and typing "cmd" and pressing Enter. Then you need to navigate to the above directory on your computer by typing "cd C:\Program Files\R\R-3.5.1\bin".

From this directory you can then type "Rscript.exe" followed by the arguments in the user guide (metadata file, input folder, base period etc.). 

I can't remember if this script is fully compatible with Windows as is but I do know people have gotten it working with little trouble.

**Comment by anuragsharma03** [comment]
![capture](https://user-images.githubusercontent.com/47248875/52285432-51708680-298c-11e9-836b-2796a40ecb2b.JPG)
Sir, I am also running the batch operation on windows. I have followed your steps (replace the foreach line) and providing the directory address but I am getting the error "there is no package called 'foreach' Execution halted". 
I have attached the screenshot, please check if I am making any error in giving directory address or there is any other reason for this error.
Also I want to mention that while installing the batch process installer package I am getting the warning message in R "foreach package missing for R 3.5.2".
I think this might be the reason for above error. On the same while I was installing "RclimPACT" it asked me to update R version so I have updated R version.

**Comment by anuragsharma03** [comment]
![capture2](https://user-images.githubusercontent.com/47248875/52287130-9649ec80-298f-11e9-9e48-ee204810c58d.JPG)
Sir, I am also running the batch opeartion on windows. I am getting error"cant open file 'climpacr2.GUI.r' : No such file or directory".
I have attached the screenshot of cmd terminal. Please tell me where I am making error in giving directory address.

**Comment by heroldn** [comment]
Yes, you should try running the commands shown in your screenshot but from within the climpact2 directory (i.e. use the "cd" command as Wendso said).
