### ISSUE TITLE
invalid class “climdexInput” object: Quantiles are missing

### ISSUE THREAD

**Issue by BWoodman** [ARCCSS-extremes/climpact2#59]
Dear Climpact2 team,

I've been having some issues calculating SPI values.
The package runs smoothly with the sample data but when I attempt to run it with my own data it returns the following error:
> Error in validObject(.Object) :
invalid class “climdexInput” object: 1: Quantiles for tmax are missing.
invalid class “climdexInput” object: 2: Quantiles for tmin are missing.
invalid class “climdexInput” object: 3: Quantiles for prec are missing.

I've been looking through the code to try to figure out where this error could be originating from but have not been able to do so. I do not understand why the quantiles are calculated fine for the sample data but not for the other dataset.
If you have any advice on this problem I would be really grateful.

I'm using daily Multi-Source Weighted-Ensemble Precipitation (MSWEP) and tempereature reanalysis data. 
I've normalized the netcdf file to the sample data. Here's the header:

> netcdf merged_hours {
dimensions:
	time = UNLIMITED ; // (12784 currently)
	lon = 52 ;
	lat = 40 ;
variables:
	double time(time) ;
		time:standard_name = "time" ;
		time:long_name = "time: mean (interval: 0h-21h UTC)" ;
		time:units = "hours since 1979-1-1 00:00:00" ;
		time:calendar = "standard" ;
		time:axis = "T" ;
	float lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	float lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	float Rainf(time, lat, lon) ;
		Rainf:standard_name = "rainfall_flux" ;
		Rainf:long_name = "Rainfall rate" ;
		Rainf:units = "kg m-2 s-1" ;
		Rainf:_FillValue = 1.e+20f ;
		Rainf:missing_value = 1.e+20f ;
		Rainf:cell_methods = "time: mean (interval: 0h-24h UTC)" ;
		Rainf:_ChunkSizes = 1, 720, 1440 ;
	float tmin(time, lat, lon) ;
		tmin:standard_name = "surface_temperature" ;
		tmin:long_name = "Average surface temperature" ;
		tmin:units = "K" ;
		tmin:_FillValue = -1.e+20f ;
		tmin:missing_value = -1.e+20f ;
		tmin:cell_methods = "time : mean" ;
		tmin:_ChunkSizes = 229, 45, 90 ;
	float tmax(time, lat, lon) ;
		tmax:standard_name = "surface_temperature" ;
		tmax:long_name = "Average surface temperature" ;
		tmax:units = "K" ;
		tmax:_FillValue = -1.e+20f ;
		tmax:missing_value = -1.e+20f ;
		tmax:cell_methods = "time : mean" ;
		tmax:_ChunkSizes = 229, 45, 90 ;
// global attributes:
		:CDI = "Climate Data Interface version 1.9.5 (http://mpimet.mpg.de/cdi)" ;
		:Conventions = "CF-1.0" ;
 
Thank you very much for your help

**Comment by heroldn** [comment]
Hi, I can't say for sure what the issue is without seeing your data.
Probably there is too much missing data in there, or unreasonable values.
If you can upload the data and the wrapper script you're using I'll take a
look. You can email me the link. And no need to normalise.

Nick.

**Comment by BWoodman** [comment]
Hi Nick,

Thank you so much for the quick response, it's really appreciated!
Upon closer inspection my precipitation data was indeed unreasonable, following a previous error in conversion. I rectified this and was able to calculate SPI values without any further problems.

I would also like to calculate SPEI values but would like to do so using a pre-existing PET dataset, and not the Hargreaves method as is used in the package. I've been trying to figure out a way to do so but have been unsuccessful as the package does not support any additional variables in the input file. If you have any advice on a work-around I would be really grateful!

Thank you very much for your help!

Best regards,

Brook

**Comment by heroldn** [comment]
Hi Brook

Unfortunately adding new variables to the input file wouldn't be trivial.
You'd be better off using the SPEI R package separately; reading in your
PET and climate data, calculating SPEI, then writing out to netcdf. Using
ncdf4 to handle netcdf files.

Cheers

Nick.

**Comment by BWoodman** [comment]
Hi Nick,

Cheers for the advice, I will give that a try!

All the best,

Brook
