### ISSUE TITLE
Does Climpact2 not check for number/percentage of missing data dates before calculating index values?

### ISSUE THREAD

**Issue by cicatrixx** [ARCCSS-extremes/climpact2#61]
In RClimDex, the monthly and annual indices were only calculated if number of missing points in the data set did not exceed a set threshold. Is similar setting not available in Climpact2?

**Comment by heroldn** [comment]
No it's not unfortunately. There is a setting similar to this for calculating the quantiles (this setting is part of the climdex.pcic package) but not what you're after. It's been mentioned before and part of some extra checks that will be added in at some point (hopefully soon).

**Comment by heroldn** [comment]
Actually, the original RClimdex functionality checked for a minimum percentage of data in the base period climatology. This functionality IS included in climdex.pcic, and thus in climpact. See the min.base.data.fraction.present parameter passed to the climdexInput.raw function, in climdex.pcic. This check is performed on calendar days.
