### ISSUE TITLE
Output of linear fit is evaluated even for indices where no value is available 

### ISSUE THREAD

**Issue by cicatrixx** [ARCCSS-extremes/climpact2#63]
In the code global variable `out` is used to store the outputs of the linear trend fitting using `lsfit`. If no indices are available due to data limitations for entire timeframe, no plots are created inside function `plotx` and error message "NO DATA TO PLOT" is shown. But the code doesn't reset the `out` variable and hence writes the last set value for `out` for the empty index series as well. I guess the climdex.pcic does have some data QC before it evaluates indices. 

Attached is a dummy input file with a lot of data holes that shows this issue in the output file. Here, multiple indices after gddgrow10 show the same trend values as gddgrow10. But the plots and data files for the indices have -99.9 for all timesteps.

[org_bad_observatory_hill_1936-2015.txt](https://github.com/ARCCSS-extremes/climpact2/files/2773073/org_bad_observatory_hill_1936-2015.txt)

[org_bad_observatory_hill_1936-2015_trend.xlsx](https://github.com/ARCCSS-extremes/climpact2/files/2773077/org_bad_observatory_hill_1936-2015_trend.xlsx)

**Comment by heroldn** [comment]
This is fixed now. See latest update.
