### ISSUE TITLE
Index IDs in trend files are not unique so would be nice to have the index description also listed in the trend files

### ISSUE THREAD

**Issue by cicatrixx** [ARCCSS-extremes/climpact2#64]
The trend summary file only lists short names of indices, which get repeated in case of indices that are estimated for both annual and monthly time frame. Would be nice if this table also included the index description to avoid any confusion and if short names are unique.

When I tried to output the values used in index plot titles as index descriptions, I found that some of the index titles have errors. In attached file, I have highlighted indices that have issues in the name or description.

[trendfile_indexnames.xlsx](https://github.com/ARCCSS-extremes/climpact2/files/2773102/trendfile_indexnames.xlsx)

**Comment by heroldn** [comment]
Thanks for the feedback, I've added a 'frequency' column so you know which index (annual or monthly) each row refers to. Note I haven't addressed the index description issues you highlighted but the output file has been fixed so I'm closing this.
