### ISSUE TITLE
Calculate indices

### ISSUE THREAD

**Issue by asharam105** [ARCCSS-extremes/climpact2#67]
I have successfully inset the data
 but when I calculate  the indices then it give error which is mention below 
Please help me

" C:\Users\DR SENA\AppData\Local\Temp\RtmpCqo5Dk\downloaded_packages
[1] R version 3.5.2 detected.
Loading required package: PCICt
Loading required package: lmomco
# Package lmomco (2.3.2) loaded [try lmomcoNews()].
Loading required package: parallel
Loading required package: ggplot2
# Package SPEI (1.7) loaded [try SPEINews()].
<Tcl>  
[1] TESTING DATA, PLEASE WAIT...
[1] climdex input object created.
[1] calculating fd\tdays\tFrost Days\tAnnual number of days when TN < 0 Â°C\tETCCDI\tT\tF,
Error in if (is.na(index.list$Annual.flag[i])) frequency = NA else { : 
  argument is of length zero
In addition: Warning messages:
1: In merge.data.frame(z, x, by = "id", all.x = F, all.y = T) :
  column names ‘NA’, ‘NA’, ‘NA’, ‘NA’ are duplicated in the result
2: In merge.data.frame(z, x, by = "id", all.x = F, all.y = T) :
  column names ‘NA’, ‘NA’, ‘NA’, ‘NA’ are duplicated in the result

**Comment by heroldn** [comment]
Hi, is all of your data in the correct format? Including the batch metadata file and missing values? Are any error text files produced?

**Comment by asharam105** [comment]
No error.   .. Thank you for give me guidance

Thank you

**Comment by heroldn** [comment]
Ok, can you attach your input files and metadata file. I'll take a look.

**Comment by asharam105** [comment]
Sorry sir...
This time ...I am out of station
..I will send it's after 2-3 days
