### ISSUE TITLE
Error when computing percentile based indices using the threshold netcdf file   

### ISSUE THREAD

**Issue by gbodeImoleayo** [ARCCSS-extremes/climpact2#68]
Hi Everyone,

I am trying to compute percentile based indices from the sample netcdf file (threshold.test.1991-1997.nc) but I get the below error after calling the climpact2.ncdf.wrapper.r.

#####################
Error in check.quantile.validity(quantiles, present.var.list, days.in.base) :
  Temperature in-base quantiles must contain 10th and 90th percentiles.
Calls: create.indices.from.files ... compute.climdex.indices -> <Anonymous> -> check.quantile.validity
######################

Please kindly assist.

Thank you.

**Comment by heroldn** [comment]
Hi. Did you make any changes to the wrapper file? And have you run the installer file?

**Comment by gbodeImoleayo** [comment]
Hi,
Thank for your prompt reply.

Yes, I did run the installer and made changes to the wrapper and was able to generate the threshold.test.1991-1997.nc with climpact2.ncdf.thresholds.wrapper.r.
But, i get the error when calling  climpact2.ncdf.wrapper.r.
Thank you.
Imoleayo
    On Monday, February 18, 2019, 4:24:04 PM GMT+9, heroldn <notifications@github.com> wrote:  
 
 
Hi. Did you make any changes to the wrapper file? And have you run the installer file?

**Comment by heroldn** [comment]
Ah, if your base period is within the date range of your data then you don't need to run the thresholds script. e.g. the sample data goes from 1990-2009, so you don't need a separate thresholds file for the base period 1991-1997, as those years are already inside your data. Basically, run the climpact2.ncdf.wrapper.r script without specifying the thresholds file.

**Comment by gbodeImoleayo** [comment]
Thanks for this clarification.
For my own data I created the threshold file from a base period of 1976-2005 and want to use another file for period of 2031-2100 to calculated the percentile based indices for two chunks (i.e. 2031-2060 and 2071-2100). This means the base period is not included in the file.
Imoleayo  

    On Monday, February 18, 2019, 4:39:05 PM GMT+9, heroldn <notifications@github.com> wrote:  
 
 
Ah, if your base period is within the date range of your data then you don't need to run the thresholds script. e.g. the sample data goes from 1990-2009, so you don't need a separate thresholds file for the base period 1991-1997, as those years are already inside your data. Basically, run the climpact2.ncdf.wrapper.r script without specifying the thresholds file.

**Comment by heroldn** [comment]
Can you send me the two wrapper files you're trying to use?

Nick.

**Comment by gbodeImoleayo** [comment]
Thank you.
Attached are the files.
    On Monday, February 18, 2019, 5:25:33 PM GMT+9, heroldn <notifications@github.com> wrote:  
 
 Can you send me the two wrapper files you're trying to use?

Nick.

**Comment by heroldn** [comment]
I don't think you can attach files to a comment. Please send them to nicholas.herold@unsw.edu.au
or paste the contents into the comment box.

**Comment by heroldn** [comment]
Please try in climpact2.ncdf.wrapper.r to use "base.range=c(1976,2005)", this is the actual base range you want to calculate the indices on, and is why you reference the thresholds file in that same script.

Let me know how you go.

**Comment by gbodeImoleayo** [comment]
Dear Nick,
Thanks for finding time to help with this issue. 
Yes, using "base.range=c(1976,2005)" in climpact2.ncdf.wrapper.r, which is the actual base range I want to calculate the indices on, worked fine without any error.
Thank you.

Imoleayo 
    On Saturday, February 23, 2019, 9:25:46 AM GMT+9, heroldn <notifications@github.com> wrote:  
 
 
Please try in climpact2.ncdf.wrapper.r to use "base.range=c(1976,2005)", this is the actual base range you want to calculate the indices on, and is why you reference the thresholds file in that same script.

Let me know how you go.
