### ISSUE TITLE
Batch processing error

### ISSUE THREAD

**Issue by izemcet** [ARCCSS-extremes/climpact2#71]
Hello,

Although I prepared the data in the correct format, I got error.txt files.

Here is the message:
Error in cbind(c("Station: ", "Latitude: ", "Longitude: ", "ClimPACT2_version: ", : object 'latitude' not found

I use R 3.6.3 and latest version of ClimPACT2 (1.2.8)

Could you help me, please?
@heroldn

**Comment by heroldn** [comment]
A bit of a late reply. Did you fix this? Let me know.
