### ISSUE TITLE
Climpact error wrapper ncdf - nc_parse_group_structure

### ISSUE THREAD

**Issue by ochee** [ARCCSS-extremes/climpact2#72]
Hello,

I'm trying to use climpact2-master and wrapper to calculate indices over ncdf files. I encountered an error, when lauching climpact2.ncdf.wrapper.r file :
`Error in nc_parse_group_structure(vars, verbose = verbose) :
  Error, trying to add dim named time  to the root group, but there is already  a dim named  time in the root group, with different length.  Have you mistakenly resued  a dimension name for two different dims?  Have you correctly specifed  the groups of any dims with duplicated names?
Calls: create.indices.from.files ... lapply -> FUN -> <Anonymous> -> nc_parse_group_structure`

Please find the structure of ncdf files used  :
`dimensions:
        time = UNLIMITED ; // (20090 currently)
        bnds = 2 ;
        Number_of_points = 8679 ;
variables:
        float time(time) ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:bounds = "time_bnds" ;
                time:units = "hours since 1950-08-01 06:00:00" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        double time_bnds(time, bnds) ;
        float Tasmax(time, Number_of_points) ;
                Tasmax:standard_name = "air_temperature" ;
                Tasmax:long_name = "Near Surface Air Temperature" ;
                Tasmax:units = "K" ;
                Tasmax:_FillValue = -9999999.f ;
                Tasmax:missing_value = -9999999.f ;
                Tasmax:cell_methods = "time: maximum" ;
        float Tasmin(time, Number_of_points) ;
                Tasmin:standard_name = "air_temperature" ;
                Tasmin:long_name = "Near Surface Air Temperature" ;
                Tasmin:units = "K" ;
                Tasmin:_FillValue = -9999999.f ;
                Tasmin:missing_value = -9999999.f ;
                Tasmin:cell_methods = "time: minimum" ;
        float Precipf(time, Number_of_points) ;
                Precipf:_FillValue = -9999999.f ;
                Precipf:missing_value = -9999999.f ;
                Precipf:cell_methods = "time: mean" ;
`
 Can this package could operate with non gridded variable, as XX (time,Number_of_points) ?

Thank you for your help,

**Comment by heroldn** [comment]
Hi Ochee, to calculate the indices on many stations you must use the batch processing functionality. This requires the input to be in text file format (one text file for each station or point), not in netcdf. The gridded netcdf functionality only works for spatial data (time,lat,lon).
